version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dental_clinic_db
    environment:
      POSTGRES_DB: dental_clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
